"""
Guidance on DataFrame handling:
1. First thing first: DataFrame is different from Matrix!
2. All saved .csv files must be a valid dataframe (explained below) when
    imported by a one-line read command (delim = ',', comment = "#", etc.)
3. No two columns shall bear the same name (especially in csv files)
4. Keep the row indices (1,2,3,...) auto-generated by the import function
5. Use long format to store those with replicates
6. Use consistent name in all .csv files
    (e.g. never have both "FcgRI" and "FcgR1", even in different files)
7. Check/sort/reorder the order of rows and cols whenever that matters
"""

using DataFrames
using CSV

function geocmean(x)
    x = convert(Vector, x)
    @. x[x <= 1.0] = 1.0
    return exp( sum(log.(x))/length(x) )
end

cellTypes = [:ncMO, :cMO, :NKs, :Neu, :EO]

function Rpho_mouse()
    df = CSV.read("../data/murine-FcgR-abundance.csv")
    df = aggregate(df, [:Cells, :Receptor], geocmean)
    df = unstack(df, :Receptor, :Cells, :Count_geocmean)
    return convert(Matrix{Float64}, df[!, cellTypes])
end
