name: format-pr

on:
  schedule:
    - cron: '0 18 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.4.2]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v2
      - name: Install JuliaFormatter and format
        run: |
          julia  -e 'import Pkg; Pkg.add("JuliaFormatter")'
          julia  -e 'using JuliaFormatter; format(".", whitespace_typedefs=true, margin=150, whitespace_ops_in_indices=true)'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Format .jl files
          title: '[AUTO] Format .jl files'
          branch: create-pull-request/format-pr
          labels: formatting, automated pr, no changelog
      - name: Check outputs
        run: |
          echo 'Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}'
          echo 'Pull Request Number - ${{ steps.cpr.outputs.pr_number }}'
